version: '3.4'

services:
  nodejs:
    container_name: bbys-analytics
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: unless-stopped
    volumes:
      - .:/web-app
      - exclude:/web-app/node_modules/
    ports:
      - "3000:3000"
    environment:
      NPM_TOKEN: ${NPM_TOKEN}
      SECRET: ${SECRET}
      SESSION_NAME: ${SESSION_NAME}
      SESSION_MAX_AGE: ${SESSION_MAX_AGE}
      SITE_URL: ${SITE_URL}
      FAUNADB_SECRET: ${FAUNADB_SECRET} 
      BIGQUERY_DATASET_ID: ${BIGQUERY_DATASET_ID}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCP_CLIENT_EMAIL: ${GCP_CLIENT_EMAIL}
      GCP_CLIENT_PRIVATE_KEY: ${GCP_CLIENT_PRIVATE_KEY}

volumes:
    exclude:
      