version: '3.4'

services:
  nodejs:
    container_name: bbys-analytics
    build:
      context: ./
    restart: unless-stopped
    ports:
      - "3004:3000"
    environment:
      NPM_TOKEN: abc
      SECRET: Secret%20!
      SESSION_NAME: _ba
      SESSION_MAX_AGE: 60
      SITE_URL: https://www.barnebys.com
      BIGQUERY_DATASET_ID: tracking_stg
      