POST http://localhost:3000/w/collect
Content-Type: application/json

[
  {
  "ref":  "user-123",
  "programId": "test-123",
  "eventCategory": "test",
  "eventAction":  "test",
  "eventLabel":  "test",
  "eventValue":  "100.0",
  "eventCurrency": "EUR"
  },
  {
    "ref":  "user-missing",
    "programId": "test-123",
    "eventCategory": "test",
    "eventAction":  "test",
    "eventLabel":  "test",
    "eventValue":  "100.0",
    "eventCurrency": "EUR"
  }
]

###
